# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Main test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        datasets: [ "datasets", "git+https://github.com/BoringDonut/datasets.git@ffmpeg-audio-read" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get install -y ffmpeg
        python -m pip librosa soundfile
        python -m pip ${{ matrix.datasets }}
    - name: Test with pytest
      run: |
        python main.py
